version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro # Windows path
      # - $HOME/.aspnet/https:/https:ro         # macOS/Linux path
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SecurePassword123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=db;Database=GargarDB;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;
    depends_on:
      - db
      - minio
    networks:
      - gargar-network

  # Other services (db, minio, etc.) remain the same...
